In [3]:
import numpy as np


In [16]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])

In [17]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [7]:
arr_2d = np.array([[1,2,3],[4,5,6]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
arr_3d = np.array([[[1,2,3],[4,5,6]],[[12,13,14],[15,16,17]]])
arr_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[12, 13, 14],
        [15, 16, 17]]])

In [15]:
arr_2d.ndim


2

In [14]:
arr_3d.ndim

3

In [18]:
arr[1:7]

array([2, 3, 4, 5, 6, 7])

In [19]:
arr_2d[0,2]

3

In [20]:
arr_2d[1,0:2]

array([4, 5])

In [21]:
arr_2d[0:2,0:1]

array([[1],
       [4]])

In [22]:
arr_2d[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [1]:
temperature_data = [25.3, 26.1, 24.8, 23.5, 27.2]
pressure_data = [101.2, 100.8, 101.5, 100.2, 101.0]
humidity_data = [55.2, 54.8, 56.5, 53.7, 55.9]

In [4]:
temperature_data = np.array([25.3, 26.1, 24.8, 23.5, 27.2])

In [5]:
pressure_data = np.array([101.2, 100.8, 101.5, 100.2, 101.0])

In [6]:
humidity_data = np.array([55.2, 54.8, 56.5, 53.7, 55.9])

In [7]:
arr1 = [[1,2],[3,4],[5,6]]

arr2 = [[6,7],[8,9],[10,11]]

res = np.concatenate((arr1, arr2))

print(res)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 6  7]
 [ 8  9]
 [10 11]]


In [8]:
arr1 = [1,2,3,4,5]

arr2 = [6,7,8,9,10]

res = np.concatenate((arr1, arr2))

print(res)

[ 1  2  3  4  5  6  7  8  9 10]


In [9]:
temp_mean = np.mean(temperature_data)

In [11]:
temp_mean

25.380000000000003

In [14]:
pressure_mean = np.mean(pressure_data)

In [15]:
pressure_mean

100.94

In [16]:
humidity_mean = np.mean(humidity_data)

In [17]:
humidity_mean

55.21999999999999

In [18]:
temp_sd = np.std(temperature_data)

In [19]:
pressure_sd = np.std(pressure_data)

In [20]:
humid_sd = np.std(humidity_data)

In [23]:
pressure_sd


0.43634848458542813

In [22]:
humid_sd

0.9579144011862429

In [24]:
t_min = np.min(temperature_data)

In [25]:
t_min

23.5

In [26]:
t_max = np.max(temperature_data)

In [27]:
t_max

27.2